services:
  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      - MB_SITE_URL=https://${MB_DOMAIN}     # ← 1) для корректных ссылок
      - MB_DB_TYPE=${MB_DB_TYPE}
      - MB_DB_DBNAME=${MB_DB_NAME}
      - MB_DB_PORT=${MB_DB_PORT}
      - MB_DB_USER=${MB_DB_USER}
      - MB_DB_PASS=${MB_DB_PASSWORD}
      - MB_DB_HOST=db
    volumes:
      - metabase-data:/metabase-data
    extra_hosts:
      - "api.gift-rolls.com:host-gateway"
    networks:
      - metabase-network
      - network                          # ← 2) подключили к общей сети

  db:
    image: postgres:17
    ports:
      - "${MB_DB_PORT}:${MB_DB_PORT}"
    environment:
      POSTGRES_DB: ${MB_DB_NAME}
      POSTGRES_USER: ${MB_DB_USER}
      POSTGRES_PASSWORD: ${MB_DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - metabase-network

volumes:
  metabase-data:
    driver: local
  db-data:
    driver: local

networks:
  metabase-network:
    name: metabase-network
  network:                               # ← 3) описали внешнюю сеть
    external: true